### ISSUE TITLE
请问有公开的模型吗？

### ISSUE THREAD

**Issue by wccccp** [gmftbyGMFTBY/Copyisallyouneed#1]
没有资源训练不起来:(

**Comment by gmftbyGMFTBY** [comment]
Thank you for your interest in our work. We plan to release the fine-tuned version CoG model and the offline phrase indexes in the future.

**Comment by wccccp** [comment]
> Thank you for your interest in our work. We plan to release the fine-tuned version CoG model and the offline phrase indexes in the future.

thank you
