### ISSUE TITLE
Question about the phrase collection

### ISSUE THREAD

**Issue by speedcell4** [gmftbyGMFTBY/Copyisallyouneed#6]
Hi, thanks for sharing the source code.

What is the average length of collected phrases? Could you please provide statistics on it? Such as how many length-1 phrases, how many length-2 phrases, and so on.
Besides, in this repo I didn't find the code of your Algorithm 1 (page 14), could you please help me out?

Thank you so much~

**Comment by speedcell4** [comment]
Besides, how high is your hit rate? I mean the percentage of *copy* vs *copy + generate*?

**Comment by gmftbyGMFTBY** [comment]
As for your first question, the code for algorithm 1 can be found at: https://github.com/gmftbyGMFTBY/Copyisallyouneed/blob/main/data/wikitext103_1024/phrase_split/phrase_split.py.

This algorithm can be understood as a simple Finite Automata Machine.

**Comment by gmftbyGMFTBY** [comment]
As for the hit rate, you could refer to table 2 in our paper.

**Comment by gmftbyGMFTBY** [comment]
The number of the length-1 phrases are the size of the vocabulary, and the number of other phrases corresponds to the specific dataset that you process.
